spring:
  application:
    name: smart-email-assistant
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

logging:
  level:
    com.example.smartemailassistant: INFO