spring:
  application:
    name: smart-email-assistant
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

# Google Gemini API Configuration
GEMINI_API_KEY: ${GEMINI_API_KEY:}

logging:
  level:
    com.example.smartemailassistant: INFO
    org.springframework.web: INFO