spring:
  application:
    name: smart-email-assistant
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  ai:
    openai:
      base-url: ${AI_BASE_URL:http://localhost:11434}
      api-key: not-needed-for-ollama
      chat:
        options:
          model: llama2

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

logging:
  level:
    com.example.smartemailassistant: INFO
    org.springframework.ai: INFO