spring:
  application:
    name: smart-email-assistant
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

# AI Configuration - FIXED: No circular reference
ai:
  base-url: ${ai.base-url:http://localhost:11434}
  model: ${ai.model:mistral}

logging:
  level:
    com.example.smartemailassistant: DEBUG