spring:
  application:
    name: smart-email-assistant
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

# Custom Ollama Configuration
AI_BASE_URL: http://localhost:11434
OLLAMA_MODEL: mistral

logging:
  level:
    com.example.smartemailassistant: DEBUG